#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import numpy as math
import matplotlib.pyplot as alt

def main():
    
    V0 = 20
    tetha = math.pi / 3
    X0 = 0
    Y0 = 0
    T = 5
    N = 100
    g = 10
    i = 0
    X = []
    Y = []
    
    X.append(X0)
    Y.append(Y0)
    
    Yex = []
    Xex = []
    Xex.append(X0)
    Yex.append(Y0)
    
    #Initiate formula
    Vx = V0 * math.cos(tetha)
    Vy = []
    Vy.append(V0 * math.sin(tetha))
    deltat = T/N
    
    for i in range (N) :
        X.append( X[i] + (Vx * deltat) )
        Vy.append( (-(g) * deltat) + Vy[i] )
        Y.append( Y[i] + (Vy[i+1] * deltat) + (g * deltaT**2) )    
        Xex.append( i * deltat * V0 * math.cos(tetha) )
        Yex.append( (-(0.5) * g * (i * deltat)**2) + (i * deltat * V0  * math.sin(tetha)) )
    

    alt.plot(X, Y, color='red', label ='Exact')
    alt.plot(Xex, Yex, color='green', label ='Numeric')
    alt.legend(loc='upper right')
    alt.xlabel("X")
    alt.ylabel("Y")    
   
    alt.show()

main()
